"""add_alerts_notifications

Revision ID: fa81130d361d
Revises: c739caefe40e
Create Date: 2026-06-02 14:18:55.551079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa81130d361d'
down_revision: Union[str, Sequence[str], None] = 'c739caefe40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notification_channel', sa.String(length=20), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('threshold >= 0.0 AND threshold <= 1.0', name='ck_alerts_threshold'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_field_id_is_active_created_at', 'alerts', ['field_id', 'is_active', 'created_at'], unique=False)
    op.create_index('ix_alerts_is_active_id', 'alerts', ['is_active', 'id'], unique=False, postgresql_where='deleted = false')
    op.create_index('ix_alerts_zone_event_type', 'alerts', ['zone', 'event_type'], unique=False)
    op.create_table('notifications',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_alert_id_status', 'notifications', ['alert_id', 'status'], unique=False, postgresql_where='deleted = false')
    op.create_index('ix_notifications_alert_id_target_date', 'notifications', ['alert_id', 'target_date'], unique=False)
    op.create_index('ix_notifications_status_id', 'notifications', ['status', 'id'], unique=False, postgresql_where='deleted = false')
    op.add_column('weather_forecasts', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_table_comment(
        'weather_forecasts',
        'Weather forecast records ingested by the ingestion job',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'weather_forecasts',
        existing_comment='Weather forecast records ingested by the ingestion job',
        schema=None
    )
    op.drop_column('weather_forecasts', 'deleted')
    op.drop_index('ix_notifications_status_id', table_name='notifications', postgresql_where='deleted = false')
    op.drop_index('ix_notifications_alert_id_target_date', table_name='notifications')
    op.drop_index('ix_notifications_alert_id_status', table_name='notifications', postgresql_where='deleted = false')
    op.drop_table('notifications')
    op.drop_index('ix_alerts_zone_event_type', table_name='alerts')
    op.drop_index('ix_alerts_is_active_id', table_name='alerts', postgresql_where='deleted = false')
    op.drop_index('ix_alerts_field_id_is_active_created_at', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
