import datetime
from uuid import UUID

from sqlalchemy import CheckConstraint, DateTime, Float, String, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base
from app.models.enums import WeatherEventType


class WeatherForecast(Base):
    __tablename__ = "weather_forecasts"
    __table_args__ = (
        # One forecast entry per zone + date + event — enforced at DB level
        UniqueConstraint("zone", "date", "event_type", name="uq_weather_forecasts_zone_date_event"),
        CheckConstraint(
            "probability >= 0.0 AND probability <= 1.0",
            name="ck_weather_forecasts_probability",
        ),
        {"comment": "Weather forecast records ingested by the ingestion job"},
    )

    # UUID generated by PostgreSQL, not Python, to avoid round-trip latency on insert
    id: Mapped[UUID] = mapped_column(primary_key=True, server_default=func.gen_random_uuid())
    zone: Mapped[str] = mapped_column(String(100))
    date: Mapped[datetime.date] = mapped_column()
    # Stored as VARCHAR(50) — enum values validated in Python, not at DB level
    event_type: Mapped[WeatherEventType] = mapped_column(String(50))
    probability: Mapped[float] = mapped_column(Float)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    # onupdate intentionally absent: ORM hooks don't fire on Core bulk statements.
    # Every update path (upsert, bulk) must set updated_at explicitly.
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
